### ISSUE TITLE
【错误】wiki共建荣誉榜页面的虚拟卡片背面的序号略有错位

### ISSUE THREAD

**Issue by Yu-Weiyi** [Chenyme/Linux-Do-Wiki#10]
此问题不重要。
如下图所示，翻转卡面后，显示的序号与背景白框有少许错位，美观度下降。
![e88252c334ba52f647a515e0aea5c453](https://github.com/user-attachments/assets/4f70e5de-595d-41eb-8349-abb28cd87ba5)

社区个人主页链接：https://linux.do/u/wayease/summary
用户名：为伊WaYease

**Comment by Chenyme** [comment]
感谢热佬！反馈有效！
编号预定：008，晚点会更新哦！
