### ISSUE TITLE
【错误】多个页面的多个异常链接

### ISSUE THREAD

**Issue by Yu-Weiyi** [Chenyme/Linux-Do-Wiki#11]
- https://wiki.linux.do/Oaifree/refresh-token 页面 更多探索栏中“进阶用法”链接 https://wiki.linux.do/Oaifree/accesstoken#2-%E9%80%9A%E8%BF%87-rf-token-%E8%8E%B7%E5%8F%96-%E8%BF%9B%E9%98%B6 失效（404）
- https://wiki.linux.do/Oaifree/access-token 页面 同上 链接 https://wiki.linux.do/Oaifree/sharetoken#2-%E9%80%9A%E8%BF%87-ac-token-%E8%8E%B7%E5%8F%96-%E8%BF%9B%E9%98%B6 失效（404）
- https://wiki.linux.do/Chat2API/api_oaipro 页面 “直接代理官方接口：” 链接 https://api.openai.com.xn--key,-jb5fijj3bfa07ojkb035eguf666aa585ynzfo0jsvgon4gsw9ega./ 异常，超链接与文字连一起了

另，建议
- https://wiki.linux.do/Oaifree/new 页面 “链接拼接：” `https://yourdomain/auth/login_share?token=SHARE_TOKEN` 链接示例修改一下排版格式。

社区个人主页链接：https://linux.do/u/wayease/summary
用户名：为伊WaYease

**Comment by Chenyme** [comment]
感谢热佬的再次反馈！同 #10 ，编号008！
