### ISSUE TITLE
【建议】这个字体颜色可以改下吗？黑色背景下，好晃眼……

### ISSUE THREAD

**Issue by viyv** [Chenyme/Linux-Do-Wiki#13]
这个字体颜色好晃眼……大佬能改下吗？
![QQ_1721825741161](https://github.com/user-attachments/assets/ee8f6ae2-fea9-4243-9e81-3addcc72e2b1)

**Comment by Chenyme** [comment]
感谢热佬反馈！今晚会更换颜色

**Comment by Chenyme** [comment]
已经改进！感谢反馈，可否留下社区链接，不留也行哈~~~( *^-^)ρ(^0^* )

**Comment by viyv** [comment]
改了就行，嘿嘿
