### ISSUE TITLE
【错误】wiki 共建荣誉榜页面 手机浏览器卡片显示

### ISSUE THREAD

**Issue by eros520** [Chenyme/Linux-Do-Wiki#19]
![IMG_5191](https://github.com/user-attachments/assets/ad1cbf2a-0c5b-4d85-b1d2-84c1c88ac220)
![IMG_5192](https://github.com/user-attachments/assets/a17e69ba-e800-4dd2-bcd3-b20502745741)

测试浏览器：safari
卡片预览显示溢出，应与上方的共建荣誉榜的卡片显示方式一致。

个人主页：https://linux.do/u/yuju

**Comment by Chenyme** [comment]
感谢热佬，后面会修复
