### ISSUE TITLE
【更正】HttpRW下的错误文本

### ISSUE THREAD

**Issue by eros520** [Chenyme/Linux-Do-Wiki#20]
HTTP 测试接口的内容中：
´´´
使用是 httpbin 的开源程序，搞了一套 http 测试接口。目前这个程序比较老，套了cf本身效果如何还未可知，回头始皇会逐步换成 php 的。
´´´
其中的第一句大概率为病句，应去除“是“字，改为“ 使用 httpbin 的开源程序”

社区主页：https://linux.do/u/yuju

**Comment by Chenyme** [comment]
感谢热佬，后续会修复！
