### ISSUE TITLE
【建议】wiki 每个页面的 slogan横幅

### ISSUE THREAD

**Issue by eros520** [Chenyme/Linux-Do-Wiki#21]
每个页面的顶部slogan横幅在手机浏览器上无法显示完全，可以适当修改格式。

![IMG_5193](https://github.com/user-attachments/assets/e9d8d47d-08d5-4d60-b40e-5cf819bfaaa0)

测试浏览器：Safari

社区主页：https://linux.do/u/yuju

**Comment by Chenyme** [comment]
感谢热佬，后续会优化此问题!
