### ISSUE TITLE
【改进】部分页面适配与歧义改进意见

### ISSUE THREAD

**Issue by tabloving** [Chenyme/Linux-Do-Wiki#22]
直奔主题：
1. header 部分的 `oai` 链接icon 在深色模式下 融入背景 不显示，如下：
![oai](https://github.com/user-attachments/assets/182f8bdb-04c8-4fd6-bd2a-f1b749d59600)

2.  [通配子域名页面](https://wiki.linux.do/Oaifree/every) 中，部分文本格式产生歧义：如下：
![01](https://github.com/user-attachments/assets/cdd94c6f-328b-40fe-bd51-0a131641728f)
`*.new.oaifree.com 的这个前缀 * ` 内容两侧 `*` 初以为是 斜体 未生效，建议使用 ` `` `包裹，如下：
`*.new.oaifree.com` 的这个前缀 ` * `

3. 如果可以，希望面包屑导航增加可点击链接🥰
![image](https://github.com/user-attachments/assets/d816ff30-3016-4b30-b783-0f8afa26f10f)
---
社区个人主页：https://linux.do/u/clarke.l/summary

**Comment by Yu-Weiyi** [comment]
对于 1：
已提交PR。

**Comment by Yu-Weiyi** [comment]
对于 2：
已提交PR。

**Comment by Yu-Weiyi** [comment]
@Chenyme 第三点那个面包屑breadcrumb我在nextra文档里没找到，你再找一找欸？

**Comment by Chenyme** [comment]
@Yu-Weiyi  好像没有，固定是这样哈哈哈
