### ISSUE TITLE
【错误】首页LOGO文本内容的颜色适配问题

### ISSUE THREAD

**Issue by tabloving** [Chenyme/Linux-Do-Wiki#26]
在 [首页](https://wiki.linux.do/)中的 LOGO 文本 `LINUX DO` ，主题切换出现颜色不醒目的问题

复现方式：

- 默认为 `浅色主题` 时，呈现如下
![image](https://github.com/user-attachments/assets/5f062b76-c4bd-4e07-8373-feb273cb584c)

- 由 `深色模式` 切换至 `浅色模式`，初始正常，刷新页面后，显示与 上述 相同

- `自动` 模式下正常，但 `自动` 切换至 `浅色模式`，与上述 相同
---
社区个人主页：https://linux.do/u/clarke.l/summary

**Comment by Chenyme** [comment]
感谢热佬，此问题会尽快修复。

可能原因是nextra框架首次进入无theme默认值，页面内切换后theme存在且LOGO正常，刷新后theme默认值丢失。
