### ISSUE TITLE
【错误】在手机浏览器模式下，这个位置应该要自适应换行才行

### ISSUE THREAD

**Issue by viyv** [Chenyme/Linux-Do-Wiki#27]
这个位置两个卡片不能像上面那样滑动，也不自适应换行，不然会超出边界，我觉得应该需要改成换行比较好
![478EB6FB-6BE4-4331-9925-58177574D818](https://github.com/user-attachments/assets/17d9f68e-45c9-4568-8df0-94d1f487a45b)

社区链接：https://linux.do/u/vasn/summary

**Comment by Yu-Weiyi** [comment]
这个问题我上午PR了，一小时前合并了，但作者应该是还没更新服务器。
重复：Issue#19 ， PR#24

**Comment by viyv** [comment]
好的，没注意，那请管理员关掉这个吧
