### ISSUE TITLE
【改进】/Linux Do/信任等级页面的说明等级的<Steps>组件序号未对齐，希望可以从0值开始

### ISSUE THREAD

**Issue by Yu-Weiyi** [Chenyme/Linux-Do-Wiki#28]
如下图，用户等级的<Steps>如果能从`0`开始就好了。
我在nextra文档里没找到更多的操作方法，可能需要考虑查看源码再入手/自行实现/引入其它组件库。
![QQ_1721979766908](https://github.com/user-attachments/assets/0a65fee9-d94d-4ec2-8419-fe2218c71df1)

**Comment by tabloving** [comment]
已提交PR，小混一手🥰

**Comment by Chenyme** [comment]
感谢热佬们的反馈和修复~！！！
