### ISSUE TITLE
【建议】关于聊天组件的输入框问题

### ISSUE THREAD

**Issue by Aboceder** [Chenyme/Linux-Do-Wiki#29]
在中文输入法的状态下，偶尔会输入一两个英文单词，正常情况下，就会直接输入，虽然显示的是拼音，但是按回车就会直接选取整个单词，但是呢，在linuxdo的聊天框里面就会出现这个情况（如下图）本来是想选单词的，但是直接发出去了，希望可以优化一下
![2024-07-26 at 15 55 14@2x](https://github.com/user-attachments/assets/dcb32b4b-a688-40ef-af9d-4444c39439bf)

**Comment by tabloving** [comment]
这边是 LINUX DO WIKI站点的维护项目哦

**Comment by Chenyme** [comment]
您好！同上面热佬所说，这里是 LINUX DO WIKI站点 的维护项目。

您可以自行前往 [Linux Do 社区 - 运营反馈](https://linux.do/c/feedback) 板块中 发帖反馈~
