### ISSUE TITLE
【更正】社区守则 页面的 不可以使用 AI 生成内容发帖 内容

### ISSUE THREAD

**Issue by eros520** [Chenyme/Linux-Do-Wiki#33]
原文内容为：不可以使用 AI 生成内容发帖 为维护中文互联网环境，这里绝对不允许使用 AI 生成内容！
但根据始皇在https://linux.do/t/topic/20234/2?u=yuju 中的相关言论，AIGC的内容是允许以截图形式发帖的。
因此应更正为：
不可以使用 AI 生成内容发布文字内容 为维护中文互联网环境，这里绝对不允许使用 AI 生成文字内容（允许以截图形式呈现）！

社区主页：https://linux.do/u/yuju

**Comment by tabloving** [comment]
这里内容来源于 LINUX DO 社区守则原文，是否需要论坛更改之后再同步。

**Comment by Chenyme** [comment]
确实是哦，我是按照社区守则引用，具体情况看始皇改不改叭！
