### ISSUE TITLE
【建议】建议在主站添加一个wiki跳转链接，还有新手注册是强制阅读wiki

### ISSUE THREAD

**Issue by viyv** [Chenyme/Linux-Do-Wiki#36]
建议在主站添加一个wiki跳转链接，还有新手注册是强制阅读wiki，不然很多人都不看。

社区链接：https://linux.do/u/vasn/summary

**Comment by Chenyme** [comment]
推荐前往 社区-运营反馈 反馈试试呀~
我也很期待主站添加 wiki 站 跳转(☆▽☆)

**Comment by Chenyme** [comment]
已在社区内反馈，始皇说后面会加个元宇宙一览😍

**Comment by viyv** [comment]
棒极了，期待！
