### ISSUE TITLE
【错误】个人空间中的资料卡片无法正确显示

### ISSUE THREAD

**Issue by JerryXu09** [Chenyme/Linux-Do-Wiki#44]
如题。使用iPad mini5访问，iPadOS16.2 Safari浏览器。

以下是**访问个人空间**时的显示页面：
![LINUX DO - WIKI](https://github.com/user-attachments/assets/091b2677-c95f-4210-a66e-6c1ef9cd5c8d)

以下是**点击卡片后，翻转几下后最终停留**的显示：
![LINUX DO - WIKI 2](https://github.com/user-attachments/assets/a290cfb4-284a-4b2c-b427-937b7b760471)

翻转过程中，卡片的位置会显示背面内容(时间很短，几乎是闪一下)，但最终不会显示背面内容，如上图。

**Comment by Chenyme** [comment]
感谢热佬！已验证 ios设备 均有此问题，后续会修复！

**Comment by Chenyme** [comment]
已修复！待会发布新版本！
