### ISSUE TITLE
【错误】用户信息页社区数据标题颜色问题

### ISSUE THREAD

**Issue by Przeblysk** [Chenyme/Linux-Do-Wiki#45]
![CleanShot2024-08-02at17 10 31@2x](https://github.com/user-attachments/assets/0050f864-09c9-4e0d-8825-a72df44cc2fc)

**Comment by Chenyme** [comment]
感谢热佬！我好像又忘记适配黑暗模式了，后续会更正！

**Comment by Przeblysk** [comment]
![CleanShot2024-08-02at17 32 29@2x](https://github.com/user-attachments/assets/b2ee0679-fbbd-4920-bb6b-ee53ddcaa13d)
嗯，看了下代码是这个h2样式中毒额color 被暗黑模式覆盖了，应该整个卡片区域的数据都没有适配暗黑模式~
可能需要单独的暗黑模式UI设计？

**Comment by Chenyme** [comment]
对的，就和之前的logo一样，没事，目前的这个布局比较丑，后面可能会换，慢慢改哈哈哈

**Comment by Chenyme** [comment]
已修复！待会发布新版本
