### ISSUE TITLE
【改进】个人页面部分适配与点击退出优化

### ISSUE THREAD

**Issue by tabloving** [Chenyme/Linux-Do-Wiki#48]
用户个人页面一些问题：
- 个人数据标题未适配 深色模式
![image](https://github.com/user-attachments/assets/57977c92-cf75-460a-b274-c1bac82e187e)
- 点击退出后不自动重定向
![image](https://github.com/user-attachments/assets/60635862-6e95-4de3-a7c7-60e12b35114e)

**Comment by Chenyme** [comment]
晚点就改！
