### ISSUE TITLE
【错误】社区守则中错误的超链接

### ISSUE THREAD

**Issue by eros520** [Chenyme/Linux-Do-Wiki#5]
https://wiki.linux.do/LinuxDo/rules
社区守则中的
```
欢迎来到本论坛！

首先欢迎大家的到来，相信这里会有不一样的感受。对了，还可以手机下载 DiscourseHub 使用本论坛。
```
其中下载DiscourseHub的超链接为错误的https://www.example.com/

正确的下载地址：
iOS：https://apps.apple.com/app/discourse-hub/id1173672076
安卓：https://play.google.com/store/apps/details?id=com.discourse&pcampaignid=web_share

**Comment by Chenyme** [comment]
感谢热佬，反馈有效！

编号预定：005，晚点会更新哦！记得提供你的社区主页噢！

**Comment by eros520** [comment]
> 感谢热佬，反馈有效！
> 
> 编号预定：005，晚点会更新哦！记得提供你的社区主页噢！

感谢佬友！
社区主页：https://linux.do/u/yuju
