### ISSUE TITLE
【建议】关于项目规范的一些建议

### ISSUE THREAD

**Issue by tabloving** [Chenyme/Linux-Do-Wiki#50]
1. 项目结构层级调整

组件部分目前都处于同级，若今后组件内容变多，全堆叠一块，或许不雅。
建议将相同类型加一层目录，例如：Card，可将card与goldcard放进去，便于未来维护查找。
趁现在内容不多，重构下层级或许简单许多。

2. 路径别名

配合 1 使用的，避免层级略深时，导入写太多 ../ ，易错且不雅

4. 格式化的统一

将编码的一些格式化工具与样式进行统一，按既定配置文件进行，避免不同格式化产生一些没必要的diff色块，不雅

5. 提交门禁

这个看具体情况吧，提一嘴 😊

**Comment by Chenyme** [comment]
好滴鹅佬！等我这个菜鸡摸索摸索完善一下

**Comment by Yu-Weiyi** [comment]
我这次重构目录一并弄了吧。

**Comment by Chenyme** [comment]
辛苦为伊佬！
