### ISSUE TITLE
【错误】linux do信用卡无法显示初始头像

### ISSUE THREAD

**Issue by woxiangfangjia** [Chenyme/Linux-Do-Wiki#52]
![image](https://github.com/user-attachments/assets/b1466d44-1326-46c2-bd7e-65134e3a9086)

详见https://linux.do/t/topic/168535

**Comment by Chenyme** [comment]
好滴佬！后续我试试能不能加上！！！

**Comment by Yu-Weiyi** [comment]
解决了，就只删了四个“/”  hhhhhhhh
