### ISSUE TITLE
【改进】社区梗百科页面图片遮挡目录（适配手机端）

### ISSUE THREAD

**Issue by jiongjiongJOJO** [Chenyme/Linux-Do-Wiki#54]
![image](https://github.com/user-attachments/assets/bb38e4d0-d4bb-4d42-a062-bae4fa34a7b9)

如图，横排的三个卡片横向太宽，遮挡住了右侧的目录

**Comment by Chenyme** [comment]
感谢佬的反馈，这个是故意这样的，nextra也有此项组件 ： bleed
其主要目的就是凸显某个文本、图像或视频，同时我感觉这样更符合 `左右护法` 的词条风格~

不过目前由于我未直接使用bleed组件，手机端显示确实有些BUG，后续会修复！

---

官方样式如下：

![image](https://github.com/user-attachments/assets/48024040-cd6e-4c5d-8534-ece1e959b914)

**Comment by Chenyme** [comment]
@Yu-Weiyi 佬辛苦！！！我看你好像已经commit了（这效率太牛逼了）？能否试试那个bleed组件？

**Comment by Yu-Weiyi** [comment]
@Chenyme 这里我这次重构给改掉了，我觉得直接放一张以前的图比放三张卡更直观。

**Comment by jiongjiongJOJO** [comment]
> 手机端显示确实有些BUG

这个是电脑端，而且是最大化窗口的情况下，不过楼上大佬已经提了PR~
