### ISSUE TITLE
【错误】带标题的链接，打开后不会自动跳转到对应的标题处

### ISSUE THREAD

**Issue by jiongjiongJOJO** [Chenyme/Linux-Do-Wiki#55]
https://wiki.linux.do/LinuxDo/code#%E5%B7%A6%E5%8F%B3%E6%8A%A4%E6%B3%95

带标题的链接，打开后不会自动跳转到对应的标题处。

![recording](https://github.com/user-attachments/assets/57ac6c9a-31cf-4504-a17f-2be44f2d69ae)

**Comment by Yu-Weiyi** [comment]
能复现，但是仅限于URL没变化的情况，只要手敲个别的#的url就能够正常定位到。
我也尝试了一下直接点刷新浏览器，是同样的现象。
我去nextra的文档那试了一下，也是这样的，屏幕闪一下原地TP。

感觉这个问题可能是nextra框架的缺陷了。 @Chenyme

**Comment by Chenyme** [comment]
框架缺陷了可能是，估计修复不了，等官方修哈哈哈
